import type { LessonContent } from "@/lib/lesson-types";

export const m06MonteCarlo: LessonContent = {
  conceptId: "m06-monte-carlo",
  prerequisiteReminder: {
    text: {
      fr: "Il faut connaître le brownien géométrique et le principe de pricing sous mesure risque-neutre.",
      en: "You need to know geometric Brownian motion and the risk-neutral pricing principle.",
    },
    conceptIds: ["m06-brownien-arithmetique-geometrique", "m06-prerequis-ito"],
  },
  glossary: [
    { term: { fr: "Trajectoire simulée (path)", en: "Simulated path" }, definition: { fr: "Une réalisation numérique complète de l'évolution du sous-jacent, générée en tirant des nombres aléatoires.", en: "A complete numerical realization of the underlying's evolution, generated by drawing random numbers." } },
  ],
  intuition: {
    fr: "Quand une formule fermée comme Black-Scholes n'existe pas (produit complexe, plusieurs sous-jacents corrélés), on peut simuler des milliers de futurs possibles du marché, calculer le payoff de l'option dans chacun, et faire la moyenne : c'est le principe de Monte-Carlo, une force brute statistique plutôt qu'une résolution mathématique exacte.",
    en: "When a closed-form formula like Black-Scholes doesn't exist (a complex product, several correlated underlyings), you can simulate thousands of possible market futures, compute the option's payoff in each, and average: this is the Monte-Carlo principle, statistical brute force rather than an exact mathematical solution.",
  },
  definition: {
    fr: "Le pricing par Monte-Carlo consiste à (1) simuler N trajectoires indépendantes du sous-jacent sous la mesure risque-neutre (donc avec drift = r, pas le vrai drift), (2) calculer le payoff de l'option pour chaque trajectoire, (3) actualiser chaque payoff au taux sans risque, et (4) faire la moyenne des N valeurs actualisées, qui converge vers le vrai prix quand N → ∞.",
    en: "Monte-Carlo pricing consists of (1) simulating N independent paths of the underlying under the risk-neutral measure (so with drift = r, not the true drift), (2) computing the option's payoff for each path, (3) discounting each payoff at the risk-free rate, and (4) averaging the N discounted values, which converges to the true price as N → ∞.",
  },
  utility: {
    fr: "Le Monte-Carlo est indispensable dès qu'aucune formule fermée n'existe : options sur panier de plusieurs actifs corrélés (M09), options path-dependent (barrières, M10), produits structurés complexes (M11) — sa flexibilité compense sa lenteur relative.",
    en: "Monte-Carlo is essential whenever no closed-form formula exists: options on a basket of several correlated assets (M09), path-dependent options (barriers, M10), complex structured products (M11) — its flexibility offsets its relative slowness.",
  },
  example: {
    fr: "Pour pricer un call européen classique (qui a pourtant une formule fermée, à titre pédagogique) : on simule 100 000 trajectoires de S_T sous la mesure risque-neutre (drift=r), on calcule max(S_T−K,0) pour chacune, on actualise chaque résultat par e^{−rT}, et on moyenne les 100 000 valeurs — le résultat converge vers le prix Black-Scholes exact quand le nombre de simulations augmente.",
    en: "To price a plain European call (which does have a closed-form formula, for teaching purposes): simulate 100,000 paths of S_T under the risk-neutral measure (drift=r), compute max(S_T−K,0) for each, discount each result by e^{−rT}, and average the 100,000 values — the result converges to the exact Black-Scholes price as the number of simulations grows.",
  },
  alternativeExplanation: {
    fr: "Pensez à estimer la probabilité qu'une pièce tombe sur pile en la lançant seulement 10 fois (résultat peu fiable) contre 1 million de fois (résultat très fiable, proche de 50%). Le Monte-Carlo applique exactement cette logique : plus on \"lance\" de trajectoires simulées, plus l'estimation du prix moyen se rapproche de la vraie valeur, à une vitesse prévisible.",
    en: "Think of estimating a coin's chance of landing heads by flipping it only 10 times (unreliable result) versus 1 million times (very reliable, close to 50%). Monte-Carlo applies exactly this logic: the more simulated paths you \"flip\", the closer the average price estimate gets to the true value, at a predictable rate.",
  },
  formula: {
    latex: "\\begin{aligned} \\hat{C} &= e^{-rT} \\times \\frac{1}{N} \\sum_{i=1}^{N} \\text{payoff}\\left(S_T^{(i)}\\right) \\\\ \\text{Erreur standard} &\\approx \\frac{\\hat{\\sigma}_{\\text{payoff}}}{\\sqrt{N}} \\end{aligned}",
    variables: [
      { symbol: "\\hat{C}", description: { fr: "Prix estimé par Monte-Carlo : moyenne des payoffs actualisés sur N trajectoires", en: "Monte-Carlo price estimate: average of the discounted payoffs over N paths" } },
      { symbol: "S_T^{(i)}", description: { fr: "Valeur simulée du sous-jacent à maturité sur la trajectoire i, sous la mesure risque-neutre", en: "Simulated value of the underlying at maturity on path i, under the risk-neutral measure" } },
      { symbol: "\\hat{\\sigma}_{\\text{payoff}}", description: { fr: "Écart-type estimé des payoffs actualisés simulés", en: "Estimated standard deviation of the simulated discounted payoffs" } },
      { symbol: "N", description: { fr: "Nombre de trajectoires simulées", en: "Number of simulated paths" } },
    ],
    assumptions: { fr: "Trajectoires simulées indépendantes et identiquement distribuées (théorème central limite).", en: "Simulated paths independent and identically distributed (central limit theorem)." },
    units: { fr: "Même unité que le prix de l'option.", en: "Same unit as the option's price." },
    example: { fr: "σ̂=15, N=10 000 : erreur standard ≈ 15/100 = 0,15 (l'estimation du prix a une incertitude d'environ ±0,15).", en: "σ̂=15, N=10,000: standard error ≈ 15/100 = 0.15 (the price estimate has an uncertainty of about ±0.15)." },
  },
  calculation: {
    fr: "1) Simuler N trajectoires de S_T sous la mesure risque-neutre (drift=r). 2) Calculer le payoff actualisé de chaque trajectoire. 3) Calculer la moyenne (l'estimation du prix) et l'écart-type de ces N valeurs. 4) L'erreur standard de l'estimation = écart-type / √N — pour diviser l'erreur par 2, il faut multiplier N par 4.",
    en: "1) Simulate N paths of S_T under the risk-neutral measure (drift=r). 2) Compute the discounted payoff of each path. 3) Compute the average (the price estimate) and standard deviation of these N values. 4) The estimate's standard error = standard deviation / √N — to halve the error, N must be multiplied by 4.",
  },
  interpretation: {
    fr: "La convergence en 1/√N est lente : quadrupler le nombre de simulations ne fait que diviser l'erreur par 2. C'est pourquoi des techniques de réduction de variance (variables antithétiques, variables de contrôle) sont couramment utilisées en pratique pour accélérer la convergence sans exploser le temps de calcul.",
    en: "Convergence at 1/√N is slow: quadrupling the number of simulations only halves the error. This is why variance-reduction techniques (antithetic variates, control variates) are commonly used in practice to speed up convergence without exploding computation time.",
  },
  pitfalls: {
    fr: "Simuler sous la mesure réelle (avec le vrai drift μ estimé de l'actif) au lieu de la mesure risque-neutre (drift=r) : une erreur qui fausse complètement le prix obtenu. Autre piège : croire qu'un grand nombre de simulations élimine toute incertitude — il reste toujours une erreur statistique résiduelle, juste plus petite, jamais nulle.",
    en: "Simulating under the real-world measure (with the asset's true estimated drift μ) instead of the risk-neutral measure (drift=r): a mistake that completely distorts the resulting price. Another trap: believing a large number of simulations eliminates all uncertainty — a residual statistical error always remains, just smaller, never zero.",
  },
  keyPoints: {
    fr: [
      "Simuler sous la mesure RISQUE-NEUTRE (drift=r), calculer le payoff, actualiser, moyenner sur N trajectoires.",
      "L'erreur standard décroît en 1/√N : une convergence lente qui motive les techniques de réduction de variance.",
      "Indispensable dès qu'aucune formule fermée n'existe (paniers, path-dependent, produits structurés).",
    ],
    en: [
      "Simulate under the RISK-NEUTRAL measure (drift=r), compute the payoff, discount, average over N paths.",
      "The standard error decreases as 1/√N: slow convergence that motivates variance-reduction techniques.",
      "Essential whenever no closed-form formula exists (baskets, path-dependent, structured products).",
    ],
  },
  advancedDemonstration: {
    fr: "Pour un produit path-dependent (M10), il faut simuler la trajectoire complète, pas seulement S_T : discrétiser [0,T] en pas Δt, et à chaque pas mettre à jour S_{t+Δt} = S_t × exp[(r−σ²/2)Δt + σ√Δt × Z], Z~N(0,1) — l'application directe du brownien géométrique (M06-2) sous mesure risque-neutre. Les techniques de réduction de variance courantes incluent les variables antithétiques (simuler aussi la trajectoire avec −Z pour chaque Z tiré, ce qui réduit la variance de l'estimateur moyen sans biais) et les variables de contrôle (utiliser un instrument similaire au prix fermé connu, comme un call vanille, pour corriger l'estimation d'un produit plus complexe).",
    en: "For a path-dependent product (M10), the full path must be simulated, not just S_T: discretize [0,T] into steps Δt, and at each step update S_{t+Δt} = S_t × exp[(r−σ²/2)Δt + σ√Δt × Z], Z~N(0,1) — the direct application of geometric Brownian motion (M06-2) under the risk-neutral measure. Common variance-reduction techniques include antithetic variates (also simulating the path with −Z for each drawn Z, which reduces the average estimator's variance without bias) and control variates (using a similar instrument with a known closed-form price, like a vanilla call, to correct the estimate for a more complex product).",
  },
};
