import type { LessonContent } from "@/lib/lesson-types";

export const m13MifidEmirKyc: LessonContent = {
  conceptId: "m13-mifid-emir-kyc",
  prerequisiteReminder: {
    text: {
      fr: "Il faut connaître les grandes familles de risque financier, en particulier le risque de contrepartie.",
      en: "You need to know the major financial risk families, particularly counterparty risk.",
    },
    conceptIds: ["m13-typologie-risques"],
  },
  glossary: [
    { term: { fr: "Compensation centrale (clearing)", en: "Central clearing" }, definition: { fr: "Le fait de faire transiter un contrat dérivé par une chambre de compensation centrale, qui devient la contrepartie de chaque partie, réduisant le risque de contrepartie bilatéral au prix d'un risque concentré sur la chambre elle-même.", en: "Routing a derivative contract through a central clearing house, which becomes each party's counterparty, reducing bilateral counterparty risk at the cost of concentrated risk on the clearing house itself." } },
    { term: { fr: "LCB-FT / AML-CFT", en: "AML-CFT" }, definition: { fr: "Lutte contre le blanchiment de capitaux et le financement du terrorisme, l'ensemble des obligations imposées aux institutions financières pour détecter et signaler les flux financiers suspects.", en: "Anti-money laundering and counter-terrorist financing, the set of obligations imposed on financial institutions to detect and report suspicious financial flows." } },
  ],
  intuition: {
    fr: "Trois réglementations distinctes structurent la façon dont les institutions financières européennes interagissent avec leurs clients et entre elles : MiFID II encadre la RELATION avec le client final (transparence, meilleure exécution), EMIR encadre les RISQUES entre institutions sur le marché des dérivés (compensation centrale, reporting), et le dispositif LCB-FT encadre l'IDENTITÉ et la légitimité des flux financiers eux-mêmes — trois angles complémentaires d'une même préoccupation : protéger l'intégrité du système financier.",
    en: "Three distinct regulations structure how European financial institutions interact with their clients and each other: MiFID II governs the RELATIONSHIP with the end client (transparency, best execution), EMIR governs RISKS between institutions in the derivatives market (central clearing, reporting), and the AML-CFT framework governs the IDENTITY and legitimacy of financial flows themselves — three complementary angles on the same concern: protecting the financial system's integrity.",
  },
  definition: {
    fr: "MiFID II (Directive 2014/65/UE, entrée en application le 3 janvier 2018 dans l'Union européenne) impose des obligations de transparence pré/post-négociation, de meilleure exécution (best execution) et de protection de l'investisseur ; sa révision (MiFID II/MiFIR review, textes entrés en vigueur le 28 mars 2024, délai de transposition des amendements fixé au 29 septembre 2025) ajuste notamment le régime de transparence et la consolidated tape européenne. EMIR (Règlement (UE) n°648/2012, révisé par EMIR 3.0 entré en vigueur le 24 décembre 2024) impose la compensation centrale obligatoire pour certains dérivés standardisés, le reporting de toutes les transactions dérivées à un référentiel central, et introduit une exigence de compte actif (Active Account Requirement, applicable depuis le 25 juin 2025) réduisant la dépendance de l'UE aux chambres de compensation de pays tiers. Le dispositif LCB-FT européen repose désormais sur le règlement AMLR (Règlement (UE) 2024/1620, application au 10 juillet 2027) et le règlement instituant l'Autorité de lutte anti-blanchiment AMLA (Règlement (UE) 2024/1624, applicable depuis le 1er juillet 2025, autorité basée à Francfort), qui remplace l'approche par directive (interprétation nationale variable) par un règlement directement applicable dans tous les États membres.",
    en: "MiFID II (Directive 2014/65/EU, entered into application on 3 January 2018 in the European Union) imposes pre/post-trade transparency, best execution and investor protection obligations; its review (MiFID II/MiFIR review, texts entered into force on 28 March 2024, amendments' transposition deadline set at 29 September 2025) notably adjusts the transparency regime and the European consolidated tape. EMIR (Regulation (EU) No 648/2012, revised by EMIR 3.0 which entered into force on 24 December 2024) imposes mandatory central clearing for certain standardized derivatives, reporting of all derivative transactions to a central trade repository, and introduces an active account requirement (applicable since 25 June 2025) reducing the EU's dependence on third-country clearing houses. The European AML-CFT framework now rests on the AMLR regulation (Regulation (EU) 2024/1620, applicable from 10 July 2027) and the regulation establishing the anti-money-laundering authority AMLA (Regulation (EU) 2024/1624, applicable since 1 July 2025, authority based in Frankfurt), which replaces the directive-based approach (variable national interpretation) with a regulation directly applicable in all member states.",
  },
  utility: {
    fr: "Comprendre ces trois cadres est indispensable pour saisir pourquoi les institutions financières européennes ont des obligations opérationnelles concrètes et coûteuses (reporting systématique de chaque transaction dérivée, vérification d'identité renforcée avant toute relation d'affaires, documentation de la meilleure exécution pour chaque ordre client) — des obligations qui ont un impact direct sur les coûts d'exploitation et donc sur les prix pratiqués envers les clients finaux.",
    en: "Understanding these three frameworks is essential to grasp why European financial institutions face concrete, costly operational obligations (systematic reporting of every derivative transaction, enhanced identity verification before any business relationship, best-execution documentation for every client order) — obligations with a direct impact on operating costs and so on prices charged to end clients.",
  },
  example: {
    fr: "Une société de gestion qui exécute un ordre pour un client doit documenter, sous MiFID II, qu'elle a obtenu le meilleur résultat possible (prix, coût, rapidité) parmi les lieux d'exécution disponibles. Si cette même société conclut un swap de taux avec une contrepartie, EMIR peut l'obliger à faire compenser ce contrat via une chambre de compensation centrale plutôt qu'en bilatéral, et à reporter la transaction à un référentiel central sous 24h. Avant même d'ouvrir la relation d'affaires avec son client, elle doit avoir mené une vérification d'identité et d'origine des fonds (KYC) conforme au dispositif LCB-FT, sous peine de sanctions administratives sévères.",
    en: "An asset manager executing a client order must, under MiFID II, document that it obtained the best possible result (price, cost, speed) among available execution venues. If that same firm enters into an interest rate swap with a counterparty, EMIR may require it to clear that contract via a central clearing house rather than bilaterally, and to report the transaction to a central trade repository within 24 hours. Before even opening the business relationship with its client, it must have conducted an identity and source-of-funds check (KYC) compliant with the AML-CFT framework, under penalty of severe administrative sanctions.",
  },
  alternativeExplanation: {
    fr: "MiFID II, EMIR et le dispositif LCB-FT sont comme trois contrôles distincts à l'entrée d'un événement important : MiFID II vérifie que chaque invité (client) reçoit un traitement transparent et équitable (meilleure place, meilleur prix) ; EMIR vérifie que les échanges entre organisateurs (institutions financières) passent par un point de contrôle central pour limiter les risques d'un défaut en chaîne ; le dispositif LCB-FT vérifie, avant même d'ouvrir la porte, que chaque invité est bien celui qu'il prétend être et que son argent a une origine légitime.",
    en: "MiFID II, EMIR and the AML-CFT framework are like three distinct checks at a major event's entrance: MiFID II verifies each guest (client) receives transparent, fair treatment (best venue, best price); EMIR verifies exchanges between organizers (financial institutions) go through a central checkpoint to limit chain-default risks; the AML-CFT framework verifies, before even opening the door, that each guest really is who they claim to be and that their money has a legitimate origin.",
  },
  formula: {
    latex: "\\text{Score de risque client} = \\sum_i w_i \\times \\text{Facteur}_i \\; (\\text{pays}, \\text{produit}, \\text{canal}, \\text{PPE})",
    variables: [
      { symbol: "\\text{Facteur}_i", description: { fr: "Chaque facteur de risque évalué (risque pays, risque produit, canal de distribution, statut de personne politiquement exposée)", en: "Each evaluated risk factor (country risk, product risk, distribution channel, politically exposed person status)" } },
      { symbol: "w_i", description: { fr: "Pondération de chaque facteur dans le score global, définie par la politique interne de gestion des risques LCB-FT de l'institution", en: "Each factor's weight in the overall score, defined by the institution's internal AML-CFT risk management policy" } },
    ],
    assumptions: { fr: "Modèle simplifié d'une approche par les risques (risk-based approach), exigée par le cadre LCB-FT plutôt qu'une checklist uniforme ; l'AMLR (2024/1620) introduit la notion de KYC perpétuel (surveillance continue, pas uniquement à l'entrée en relation).", en: "Simplified model of a risk-based approach, required by the AML-CFT framework rather than a uniform checklist; AMLR (2024/1620) introduces the concept of perpetual KYC (continuous monitoring, not just at onboarding)." },
    units: { fr: "Score sans dimension, utilisé pour classer le client en catégorie de risque (faible/standard/élevé).", en: "Dimensionless score, used to classify the client into a risk category (low/standard/high)." },
    example: { fr: "Un client situé dans une juridiction à risque élevé, effectuant des transactions via un canal non-face-à-face, et identifié comme personne politiquement exposée, cumule plusieurs facteurs de risque élevé, déclenchant une vigilance renforcée (enhanced due diligence).", en: "A client located in a high-risk jurisdiction, transacting via a non-face-to-face channel, and identified as a politically exposed person, accumulates several high-risk factors, triggering enhanced due diligence." },
  },
  calculation: {
    fr: "1) Pour MiFID II : documenter systématiquement, pour chaque ordre client, les facteurs de meilleure exécution considérés et le lieu d'exécution choisi. 2) Pour EMIR : identifier si un dérivé est soumis à l'obligation de compensation centrale, reporter chaque transaction au référentiel central compétent, et vérifier l'application de l'Active Account Requirement le cas échéant. 3) Pour le dispositif LCB-FT : calculer un score de risque client selon une approche par les risques, appliquer une vigilance proportionnée (standard ou renforcée), et surveiller la relation de façon continue (KYC perpétuel) plutôt qu'une vérification ponctuelle initiale.",
    en: "1) For MiFID II: systematically document, for each client order, the best-execution factors considered and the chosen execution venue. 2) For EMIR: identify whether a derivative is subject to the central clearing obligation, report each transaction to the competent central trade repository, and check the Active Account Requirement's application where relevant. 3) For the AML-CFT framework: compute a client risk score under a risk-based approach, apply proportionate due diligence (standard or enhanced), and continuously monitor the relationship (perpetual KYC) rather than a one-off initial check.",
  },
  interpretation: {
    fr: "Ces trois cadres ne sont pas de simples formalités administratives : le non-respect de l'obligation de meilleure exécution (MiFID II), de compensation centrale ou de reporting (EMIR), ou de vigilance LCB-FT expose l'institution à des sanctions réglementaires significatives et à un risque réputationnel majeur. Le passage d'un cadre par directive (interprétation nationale variable) à un cadre par règlement (application uniforme, cas de l'AMLR) signale une volonté européenne d'harmonisation renforcée face à des lacunes constatées dans l'application antérieure.",
    en: "These three frameworks aren't mere administrative formalities: failing to meet best-execution obligations (MiFID II), central clearing or reporting (EMIR), or AML-CFT due diligence exposes the institution to significant regulatory sanctions and major reputational risk. The shift from a directive-based framework (variable national interpretation) to a regulation-based one (uniform application, the AMLR's case) signals a European push for stronger harmonization in response to gaps observed in prior application.",
  },
  pitfalls: {
    fr: "Croire que ces trois réglementations sont figées : leurs révisions successives (MiFID II/MiFIR review en 2024, EMIR 3.0 fin 2024, refonte complète du dispositif LCB-FT avec l'AMLR/AMLA en 2024-2027) montrent un cadre réglementaire européen en évolution continue, avec des dates d'application échelonnées sur plusieurs années qu'il faut suivre précisément. Autre piège : confondre le KYC ponctuel réalisé à l'entrée en relation avec l'exigence de surveillance continue (KYC perpétuel) introduite par l'AMLR, qui change fondamentalement l'approche opérationnelle des institutions.",
    en: "Believing these three regulations are fixed: their successive revisions (MiFID II/MiFIR review in 2024, EMIR 3.0 late 2024, complete overhaul of the AML-CFT framework with AMLR/AMLA in 2024-2027) show a European regulatory framework in continuous evolution, with application dates staggered over several years that must be precisely tracked. Another trap: confusing one-off KYC performed at onboarding with the continuous monitoring requirement (perpetual KYC) introduced by AMLR, which fundamentally changes institutions' operational approach.",
  },
  keyPoints: {
    fr: [
      "MiFID II encadre la relation avec le client final (transparence, meilleure exécution) ; sa révision est entrée en vigueur le 28 mars 2024.",
      "EMIR (révisé par EMIR 3.0, en vigueur depuis le 24 décembre 2024) encadre le risque de contrepartie entre institutions via la compensation centrale et le reporting.",
      "Le dispositif LCB-FT européen passe d'une directive à un règlement directement applicable (AMLR, Règlement (UE) 2024/1620, application au 10 juillet 2027), avec une nouvelle autorité dédiée (AMLA, opérationnelle depuis le 1er juillet 2025).",
    ],
    en: [
      "MiFID II governs the relationship with the end client (transparency, best execution); its review entered into force on 28 March 2024.",
      "EMIR (revised by EMIR 3.0, in force since 24 December 2024) governs counterparty risk between institutions via central clearing and reporting.",
      "The European AML-CFT framework shifts from a directive to a directly applicable regulation (AMLR, Regulation (EU) 2024/1620, applicable from 10 July 2027), with a new dedicated authority (AMLA, operational since 1 July 2025).",
    ],
  },
  advancedDemonstration: {
    fr: "L'Active Account Requirement introduit par EMIR 3.0 illustre un objectif de souveraineté financière européenne peu discuté hors des cercles spécialisés : en obligeant les contreparties européennes à maintenir un compte actif auprès d'une chambre de compensation établie dans l'UE pour certains dérivés jugés systémiques (plutôt que de dépendre exclusivement de chambres de compensation de pays tiers, notamment britanniques post-Brexit), le régulateur cherche à réduire un risque de concentration géographique identifié comme une vulnérabilité structurelle pour la stabilité financière de la zone — un exemple concret de la façon dont la réglementation des dérivés (théoriquement une question de gestion du risque de contrepartie, M13-risques-d) devient aussi un instrument de politique économique et géopolitique.",
    en: "The Active Account Requirement introduced by EMIR 3.0 illustrates a European financial sovereignty objective rarely discussed outside specialist circles: by requiring European counterparties to maintain an active account with an EU-established clearing house for certain derivatives deemed systemic (rather than relying exclusively on third-country clearing houses, notably UK ones post-Brexit), the regulator seeks to reduce a geographic concentration risk identified as a structural vulnerability to the area's financial stability — a concrete example of how derivatives regulation (theoretically a matter of counterparty risk management, M13-risques-d) also becomes an instrument of economic and geopolitical policy.",
  },
};
