import type { ConceptDef } from "../types";

export const m03: ConceptDef[] = [
  {
    id: "m03-definition-obligations",
    chapterId: "m03",
    sourceRef: "M03-1",
    level: "essential",
    estimatedMinutes: 5,
    status: "published",
    title: { fr: "Définition et types d'obligations", en: "Bond definition & types" },
    objective: {
      fr: "Décrire les propriétés et types d'obligations, y compris les zéro-coupons.",
      en: "Describe bond properties and types, including zero-coupon bonds.",
    },
  },
  {
    id: "m03-pricing-obligation",
    chapterId: "m03",
    sourceRef: "M03-2",
    level: "essential",
    estimatedMinutes: 7,
    status: "published",
    title: { fr: "Pricing d'une obligation", en: "Bond pricing" },
    objective: {
      fr: "Calculer le prix d'une obligation par actualisation des flux, avec coupon couru, clean/dirty price et rendement actuariel.",
      en: "Price a bond by discounting cash flows, with accrued coupon, clean/dirty price and yield to maturity.",
    },
  },
  {
    id: "m03-duration",
    chapterId: "m03",
    sourceRef: "M03-3",
    level: "essential",
    estimatedMinutes: 7,
    status: "published",
    title: { fr: "Duration de Macaulay et duration modifiée", en: "Macaulay duration & modified duration" },
    objective: {
      fr: "Calculer et interpréter la duration de Macaulay et la duration modifiée d'une obligation.",
      en: "Compute and interpret a bond's Macaulay duration and modified duration.",
    },
  },
  {
    id: "m03-convexite",
    chapterId: "m03",
    sourceRef: "M03-4",
    level: "advanced",
    estimatedMinutes: 7,
    status: "published",
    title: { fr: "Convexité", en: "Convexity" },
    objective: {
      fr: "Calculer la convexité et l'utiliser pour approximer la relation prix-taux.",
      en: "Compute convexity and use it to approximate the price-yield relationship.",
    },
  },
  {
    id: "m03-risque-credit",
    chapterId: "m03",
    sourceRef: "M03-5",
    level: "essential",
    estimatedMinutes: 5,
    status: "published",
    title: { fr: "Risque de crédit et notation", en: "Credit risk & ratings" },
    objective: {
      fr: "Expliquer le risque de crédit, le rôle des agences de notation et les limites des notations.",
      en: "Explain credit risk, the role of rating agencies and the limits of ratings.",
    },
  },
  {
    id: "m03-cds",
    chapterId: "m03",
    sourceRef: "M03-6",
    level: "advanced",
    estimatedMinutes: 6,
    status: "published",
    title: { fr: "Mécanisme d'un CDS", en: "CDS mechanics" },
    objective: {
      fr: "Décrire acheteur/vendeur de protection, prime, événement de crédit et règlement d'un CDS.",
      en: "Describe protection buyer/seller, premium, credit event and settlement of a CDS.",
    },
  },
  {
    id: "m03-repo-collateral",
    chapterId: "m03",
    sourceRef: "M03-7",
    level: "essential",
    estimatedMinutes: 6,
    status: "published",
    title: { fr: "Marché du repo et prêt de titres", en: "Repo market & securities lending" },
    objective: {
      fr: "Décrire le mécanisme d'une mise en pension (repo), le rôle du collatéral et de la décote, et le lien avec le taux sans risque.",
      en: "Describe how a repurchase agreement (repo) works, the role of collateral and haircuts, and the link to the risk-free rate.",
    },
  },
  {
    id: "m03-taux-sans-risque",
    chapterId: "m03",
    sourceRef: "M03-8",
    level: "essential",
    estimatedMinutes: 5,
    status: "published",
    title: { fr: "Taux sans risque, spot et forward", en: "Risk-free, spot & forward rates" },
    objective: {
      fr: "Choisir un proxy de taux sans risque et distinguer taux spot, taux forward et conventions de courbe.",
      en: "Choose a risk-free rate proxy and distinguish spot rates, forward rates and curve conventions.",
    },
  },
  {
    id: "m03-dv01",
    chapterId: "m03",
    sourceRef: "M03-9",
    level: "advanced",
    estimatedMinutes: 6,
    status: "published",
    title: { fr: "DV01 / PV01", en: "DV01 / PV01" },
    objective: {
      fr: "Définir et calculer le DV01 (PV01), son unité et sa convention de signe.",
      en: "Define and compute DV01 (PV01), its unit and sign convention.",
    },
  },
  {
    id: "m03-cs01",
    chapterId: "m03",
    sourceRef: "M03-10",
    level: "advanced",
    estimatedMinutes: 6,
    status: "published",
    title: { fr: "CS01 : sensibilité au spread de crédit", en: "CS01: credit spread sensitivity" },
    objective: {
      fr: "Définir le CS01 comme analogue du DV01 pour le spread de crédit, et l'utiliser pour estimer une variation de valeur.",
      en: "Define CS01 as the credit-spread analog of DV01, and use it to estimate a value change.",
    },
  },
  {
    id: "m03-sensibilite-courbe",
    chapterId: "m03",
    sourceRef: "M03-11",
    level: "advanced",
    estimatedMinutes: 7,
    status: "published",
    title: { fr: "DV01 par maturité et déformations de la courbe (pentification/aplatissement)", en: "DV01 by maturity & curve shape changes (steepening/flattening)" },
    objective: {
      fr: "Décomposer le DV01 par tranche de maturité (key rate duration) et interpréter une pentification/aplatissement de la courbe des taux.",
      en: "Break down DV01 by maturity bucket (key rate duration) and interpret a steepening/flattening of the yield curve.",
    },
  },
  {
    id: "m03-carry-roll-down",
    chapterId: "m03",
    sourceRef: "M03-12",
    level: "advanced",
    estimatedMinutes: 7,
    status: "published",
    title: { fr: "Carry et roll-down sur la courbe des taux", en: "Carry & roll-down on the yield curve" },
    objective: {
      fr: "Distinguer carry et roll-down comme sources de gain d'une position obligataire même si les taux ne bougent pas.",
      en: "Distinguish carry and roll-down as sources of gain on a bond position even if rates don't move.",
    },
  },
  {
    id: "m03-obligations-convertibles",
    chapterId: "m03",
    sourceRef: "M03-13",
    level: "advanced",
    estimatedMinutes: 7,
    status: "published",
    title: { fr: "Obligations convertibles", en: "Convertible bonds" },
    objective: {
      fr: "Décrire une obligation convertible comme obligation + option de conversion en actions, et situer son prix entre plancher obligataire et valeur de conversion.",
      en: "Describe a convertible bond as a bond + conversion option into equity, and locate its price between the bond floor and the conversion value.",
    },
  },
];
