import type { ConceptDef } from "../types";

export const m08: ConceptDef[] = [
  {
    id: "m08-volatilite-realisee",
    chapterId: "m08",
    sourceRef: "M08-1",
    level: "essential",
    estimatedMinutes: 6,
    status: "published",
    title: { fr: "Volatilité réalisée", en: "Realized volatility" },
    objective: {
      fr: "Calculer la volatilité réalisée : rendements simples/logarithmiques, fréquence, annualisation.",
      en: "Compute realized volatility: simple/log returns, frequency, annualization.",
    },
  },
  {
    id: "m08-volatilite-implicite",
    chapterId: "m08",
    sourceRef: "M08-2",
    level: "essential",
    estimatedMinutes: 6,
    status: "published",
    title: { fr: "Volatilité implicite", en: "Implied volatility" },
    objective: {
      fr: "Extraire une volatilité implicite d'un prix et en connaître les propriétés.",
      en: "Extract implied volatility from a price and know its properties.",
    },
  },
  {
    id: "m08-skew-smile-surface",
    chapterId: "m08",
    sourceRef: "M08-3",
    level: "advanced",
    estimatedMinutes: 7,
    status: "published",
    title: { fr: "Skew, smile et surface de volatilité", en: "Skew, smile & volatility surface" },
    objective: {
      fr: "Décrire skew, smile, structure par terme et surface/nappe de volatilité.",
      en: "Describe skew, smile, term structure and the volatility surface.",
    },
  },
  {
    id: "m08-formes-skew-smile",
    chapterId: "m08",
    sourceRef: "M08-4",
    level: "advanced",
    estimatedMinutes: 6,
    status: "published",
    title: { fr: "Formes courantes du skew equity et du smile FX", en: "Common shapes of equity skew & FX smile" },
    objective: {
      fr: "Étudier les formes courantes du skew equity et du smile FX, en précisant leur dépendance au marché et à la date.",
      en: "Study common shapes of equity skew and FX smile, noting their dependence on market and date.",
    },
  },
  {
    id: "m08-variance-swap",
    chapterId: "m08",
    sourceRef: "M08-5",
    level: "advanced",
    estimatedMinutes: 8,
    status: "published",
    title: { fr: "Variance swap", en: "Variance swap" },
    objective: {
      fr: "Définir le payoff d'un variance swap, son utilisation, sa réplication et son pricing.",
      en: "Define a variance swap's payoff, its use, replication and pricing.",
    },
  },
  {
    id: "m08-replication-echange-ecart",
    chapterId: "m08",
    sourceRef: "M08-6",
    level: "advanced",
    estimatedMinutes: 6,
    status: "upcoming",
    needsClarification: true,
    title: { fr: "« Réplication d'un échange d'écart » — terme à confirmer", en: "\"Replication of a spread exchange\" — term to confirm" },
    objective: {
      fr: "Intitulé fourni par le cadrage, probablement lié à la réplication du variance swap ; conservé tel quel en attendant confirmation (voir README, section E).",
      en: "Title supplied by the brief, probably related to variance swap replication; kept as-is pending confirmation (see README, section E).",
    },
  },
  {
    id: "m08-vol-locale-stochastique",
    chapterId: "m08",
    sourceRef: "M08-7",
    level: "advanced",
    estimatedMinutes: 8,
    status: "published",
    title: { fr: "Volatilité locale et volatilité stochastique", en: "Local volatility & stochastic volatility" },
    objective: {
      fr: "Comparer principes, calibration, différences, usages et limites des modèles de vol locale et vol stochastique.",
      en: "Compare principles, calibration, differences, uses and limits of local and stochastic volatility models.",
    },
  },
  {
    id: "m08-modele-avellaneda",
    chapterId: "m08",
    sourceRef: "M08-8",
    level: "advanced",
    estimatedMinutes: 7,
    status: "upcoming",
    needsClarification: true,
    title: { fr: "Modèle d'Avellaneda — référence à préciser", en: "Avellaneda model — reference to confirm" },
    objective: {
      fr: "Sujet conservé explicitement ; référence exacte à confirmer avant rédaction, sans le confondre avec Avellaneda-Stoikov (market making, voir README section E).",
      en: "Topic explicitly kept; exact reference to confirm before writing, not to be confused with Avellaneda-Stoikov (market making, see README section E).",
    },
  },
];
