import type { ConceptDef } from "../types";

export const m10: ConceptDef[] = [
  {
    id: "m10-mecanismes-barrieres",
    chapterId: "m10",
    sourceRef: "M10-1",
    level: "advanced",
    estimatedMinutes: 7,
    status: "upcoming",
    title: { fr: "Mécanismes des options barrières", en: "Barrier option mechanics" },
    objective: {
      fr: "Décrire knock-in/knock-out, up/down, observation continue/discrète et rebates avec exemples.",
      en: "Describe knock-in/knock-out, up/down, continuous/discrete observation and rebates with examples.",
    },
  },
  {
    id: "m10-greeks-barrieres",
    chapterId: "m10",
    sourceRef: "M10-2",
    level: "advanced",
    estimatedMinutes: 7,
    status: "upcoming",
    title: { fr: "Sensibilités autour de la barrière", en: "Sensitivities around the barrier" },
    objective: {
      fr: "Représenter graphiquement les Greeks autour de la barrière et connaître leurs limites.",
      en: "Graph the Greeks around the barrier and know their limits.",
    },
  },
  {
    id: "m10-barrier-parity",
    chapterId: "m10",
    sourceRef: "M10-3",
    level: "advanced",
    estimatedMinutes: 6,
    status: "upcoming",
    title: { fr: "Barrier parity / in-out parity", en: "Barrier parity / in-out parity" },
    objective: {
      fr: "Définir la barrier parity (in-out parity) et ses hypothèses nécessaires.",
      en: "Define barrier parity (in-out parity) and its necessary assumptions.",
    },
  },
  {
    id: "m10-pdi",
    chapterId: "m10",
    sourceRef: "M10-4",
    level: "advanced",
    estimatedMinutes: 7,
    status: "upcoming",
    title: { fr: "Étude de cas : put down-and-in (PDI)", en: "Case study: put down-and-in (PDI)" },
    objective: {
      fr: "Analyser un put down-and-in : risques, hedging et sensibilités.",
      en: "Analyze a put down-and-in: risks, hedging and sensitivities.",
    },
  },
  {
    id: "m10-impact-vol-knockout",
    chapterId: "m10",
    sourceRef: "M10-5",
    level: "advanced",
    estimatedMinutes: 6,
    status: "upcoming",
    title: { fr: "Impact de la volatilité sur les knock-out", en: "Volatility impact on knock-outs" },
    objective: {
      fr: "Évaluer l'impact de la volatilité sur les knock-out et le déplacement de barrière, en distinguant changement contractuel et ajustement de modélisation.",
      en: "Assess volatility's impact on knock-outs and barrier shifting, distinguishing contractual change from modeling adjustment.",
    },
  },
  {
    id: "m10-doubles-barrieres",
    chapterId: "m10",
    sourceRef: "M10-6",
    level: "advanced",
    estimatedMinutes: 6,
    status: "upcoming",
    title: { fr: "Doubles-barrières", en: "Double barriers" },
    objective: {
      fr: "Décrire le mécanisme et le fonctionnement des options à double barrière.",
      en: "Describe the mechanism and functioning of double-barrier options.",
    },
  },
  {
    id: "m10-options-digitales",
    chapterId: "m10",
    sourceRef: "M10-7",
    level: "advanced",
    estimatedMinutes: 6,
    status: "upcoming",
    title: { fr: "Options digitales", en: "Digital options" },
    objective: {
      fr: "Décrire le mécanisme cash-or-nothing/asset-or-nothing, le payoff et les Greeks d'une digitale.",
      en: "Describe the cash-or-nothing/asset-or-nothing mechanism, the payoff and the Greeks of a digital option.",
    },
  },
  {
    id: "m10-replication-digitale",
    chapterId: "m10",
    sourceRef: "M10-8",
    level: "advanced",
    estimatedMinutes: 6,
    status: "upcoming",
    title: { fr: "Réplication d'une digitale par spreads", en: "Digital replication via spreads" },
    objective: {
      fr: "Répliquer une digitale par des spreads et connaître les limites près du strike/seuil.",
      en: "Replicate a digital option using spreads and know the limits near the strike/threshold.",
    },
  },
  {
    id: "m10-lissage-delta-gamma",
    chapterId: "m10",
    sourceRef: "M10-9",
    level: "advanced",
    estimatedMinutes: 6,
    status: "upcoming",
    title: { fr: "Lissage du Delta et du Gamma près du seuil", en: "Smoothing Delta and Gamma near the threshold" },
    objective: {
      fr: "Décrire les méthodes de lissage du Delta et du Gamma autour du seuil/de la barrière, leurs compromis et risque résiduel.",
      en: "Describe methods to smooth Delta and Gamma around the threshold/barrier, their trade-offs and residual risk.",
    },
  },
];
